# docker-compose up
# docker-compose down

version : '3.7'
services :
  backend :
    build : 
      context : ./java/simple-api
      args :
        it : 1
    container_name : java
    networks :
      - back-network
    depends_on :
      - "database"
  database :
    build : 
      context : ./pgsql
      args :
        e: POSTGRES_PASSWORD=123
    container_name : pgsql
    volumes:
      - /my/own/datadir:/var/lib/postgresql/data
    networks :
      - back-network
  httpd :
    build : 
      context : ./httpd
      args : 
        dit: 1
    container_name : httpd
    ports :
      - "80:80"
    networks :
      - back-network
    depends_on :
      - "backend"
networks :
  back-network:
    driver: bridge